version: '3'

services:

        app:
           build: docker
           container_name: my-app
           volumes:
              - ./app:/app
              - ./docker/logs:/var/log/apache2
           ports:
              - "80:80"
              
        composer:
           image: composer
           volumes:
              - ./app:/app

        database:
           container_name: my-database
           image: postgres
           ports:
             - "5432:5432"
           environment:
              - "POSTGRES_DB: postgres"
              - "POSTGRES_USER: postgres"
              - "POSTGRES_PASSWORD: postgres"

        adminer:
           container_name: my-adminer
           image: adminer
           ports:
              - 8080:8080