version: '3'

services:

        app:
           build: docker
           volumes:
              - .app:/var/www/html
           ports:
              - "80:80"
              
        composer:
           image: composer
           volumes:
              - .app:/var/www/html

        database:
           image: postgres
           environment:
              - POSTGRES_DB: postgres
              - POSTGRES_USER: postgres
              - POSTGRES_PASSWORD: postgres

        adminer:
           image: adminer
           ports:
              - 8080:8080